### ISSUE TITLE
I keep crashing while spawning the gulper eel

### ISSUE THREAD

**Issue by Venturge** [DominicKarma/InfernumModePublic#1]
I checked the logs and this was written at the exact hour I crashed : 
[17:34:58.533] [Main Thread/WARN] [FNA]: KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_CARET SDL_SCANCODE_LEFTBRACKET
[17:34:58.567] [Main Thread/WARN] [FNA]: KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_CARET SDL_SCANCODE_LEFTBRACKET
[17:34:58.833] [Main Thread/WARN] [FNA]: KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_CARET SDL_SCANCODE_LEFTBRACKET
[17:34:58.933] [Main Thread/WARN] [FNA]: KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_CARET SDL_SCANCODE_LEFTBRACKET

**Comment by NerfDave** [comment]
I'm also getting a crash when a reaper shark spawns. Maybe linked?

**Comment by toasty599** [comment]
Is this still an issue?

**Comment by ZapGamer** [comment]
i was in the abyss farming just now and the game crashed randomly, so yes...

**Comment by Stachelbeere1248** [comment]
Gulper eel is def. crashing for me as well

**Comment by ZapGamer** [comment]
Ok i'm now in .28 and a Gulper eel spawned naturally without crashing my game. i'm also playing in multiplayer with a friend and i was the only one getting this problem.

**Comment by Venturge** [comment]
maybe it's because it's not the same mod anymore, it was reposted when the mod changed owner

**Comment by Venturge** [comment]
Nevermind I'm still crashing

**Comment by Stachelbeere1248** [comment]
bro this random ass mob hits my pc harder than supreme calamitas

**Comment by toasty599** [comment]
Send a log file please.

**Comment by Stachelbeere1248** [comment]
For me personally at least it literally just crashes without logging anything as I already mentioned.

> I am also not getting any outputs in the logs besides this in terrariasteamclient.log `[14:43:05.858] [Main Thread/INFO] [TerrariaSteamClient]: The connection to tML was closed unexpectedly. Look in client.log or server.log for details` client.log literally just ends with `[Main Thread/INFO] [Terraria]: Entering world with player: ...`

**Comment by toasty599** [comment]
With nothing useful in the logs, I don't really have anything to work off with this, so it will be closed until further notice.
