### ISSUE TITLE
"InfernumMode: Load Failed" on world load

### ISSUE THREAD

**Issue by marlux895** [DominicKarma/InfernumModePublic#10]
While creating and playing a fresh Infernum world works just fine, I've experienced this same error several times when trying to load into a world on a different day (I don't know if that's relevant).
The error seemed to have vanished randomly based on my experience trying to play in a different world/save a few days back.
This is all while in singleplayer.
Here is a screenshot and the logs file.
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12282215/client.log)
![FdhONkvJxA](https://github.com/DominicKarma/InfernumModePublic/assets/141656905/45edf92b-3ce5-4cb2-ad62-f1d9e5c82970)

**Comment by toasty599** [comment]
Check closed issues, this has already been seen and adressed.

**Comment by marlux895** [comment]
I was unaware, sorry and thank you. Glad I'm not crazy.
