### ISSUE TITLE
Unable to search for items with Journey mode search tab 

### ISSUE THREAD

**Issue by lllllSkarf** [DominicKarma/InfernumModePublic#104]
When I try to type in the search tab, the screen just flickers and then the items don't refresh as they should. It started happening yesterday and I disabled every mod I had and re-enabled one by one, to find that Infernum was the one causing problems

Thanks for your time

**Comment by zium1337** [comment]
same

**Comment by FlashBang12** [comment]
I am having the exact same problem, I dunno what's going on but I hope it's able to be found. I have an error log just in case anyone asks for it.

**Comment by Habble53** [comment]
> 4- Any relevant media such as images or videos showcasing the issue, if applicable.
> 5- If the issue is an in-game bug, attach the client.log and server.log (if multiplayer).

These are supposed to be readily available if you want help solving this issue. Mainly the log files.

**Comment by FlashBang12** [comment]
> 

Here are my logs: I have used different Journey Mode mods and they seem to have no effect, it still decides to break regardless. Here they are: 
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12565403/client.log)
[client (1).log](https://github.com/DominicKarma/InfernumModePublic/files/12565404/client.1.log)

These are both the logs, different things, I even disabled and enabled everything and it seems that Infernum just has an issue with Journey mode

**Comment by FlashBang12** [comment]
> > 4- Any relevant media such as images or videos showcasing the issue, if applicable.
> > 5- If the issue is an in-game bug, attach the client.log and server.log (if multiplayer).
> 
> These are supposed to be readily available if you want help solving this issue. Mainly the log files.

Hopefully that helps, I don't think the quote reply was done right so there it is lol

**Comment by toasty599** [comment]
Fixed for next patch
