### ISSUE TITLE
eidolon wyrm 2nd phase bug

### ISSUE THREAD

**Issue by BigNick69** [DominicKarma/InfernumModePublic#107]
When activating the eidolon wyrm fight it works perfectly fine until it does a attack when roughly half health and then crashes my game. ive had my 3 other friends try this in singleplayer and its very repeatable.

https://github.com/DominicKarma/InfernumModePublic/assets/133547389/65cc24d2-53fd-49be-bc48-1e833e3c8bb9

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12569766/client.log)

**Comment by Habble53** [comment]
> 5- If the issue is an in-game bug, attach the client.log and server.log (if multiplayer).

Please have these log files readily available

**Comment by toasty599** [comment]
Logs.

**Comment by BigNick69** [comment]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12569768/client.log)

**Comment by BigNick69** [comment]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12569770/client.log)

**Comment by toasty599** [comment]
Fixed for next patch
