### ISSUE TITLE
your mod ia not working properly with fargo soul mod 

### ISSUE THREAD

**Issue by heftycool98** [DominicKarma/InfernumModePublic#109]
so i start new world and player and when i trun on eternity mode with Infernum Mode on all nps that was spawn disappear and dosnt spawn back and mob also dont  spawn too so i dsiable your  mod through mod broswer   and after that with eternity mode npc spawn back and mob too even with infernum mode off with eternity mode on npc not spawning back

**Comment by toasty599** [comment]
Cross modding is not our job to.
