### ISSUE TITLE
Aquatic Scourge

### ISSUE THREAD

**Issue by Raqnick** [DominicKarma/InfernumModePublic#111]
I have some problems with this boss.I have this:
Or i have only head of the Worm 
Or i have only head if it and it's takes zero damage
Or i have body and head,but game's crashing
Playing in multiplayer,
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12580174/client.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12590046/server.log)

**Comment by Godslayer40000** [comment]
if your playing in mp they want the other log specified aswell

**Comment by Raqnick** [comment]
Can you say please what exactly log ?

**Comment by Godslayer40000** [comment]
no I have better things to do than find it again, go find it like the devs expect you to and like the rest of us

**Comment by toasty599** [comment]
Probably fixed?
