### ISSUE TITLE
Profaned Guardians don't want to spawn.

### ISSUE THREAD

**Issue by chaapz** [DominicKarma/InfernumModePublic#112]
When I stand on the ledge and try to spawn them, it doesn't work. The biome's correct, the time's correct, they just don't spawn. I even went through the entire arena clicking, and it didn't work.

I also checked, just in case, and it's not a multiplayer issue.

if it helps, this is the map of the area.
![20230912175048_1](https://github.com/DominicKarma/InfernumModePublic/assets/102792004/5b65cc39-84b4-42d3-83ea-0840c1f2c431)

**Comment by toasty599** [comment]
#90 Please check existing issues.
