### ISSUE TITLE
Journey Mode Duplication Search Bar Bugged

### ISSUE THREAD

**Issue by SoppyDrop** [DominicKarma/InfernumModePublic#114]
Greetings, I seem to have a problem with the journey mode search bar when using Infernum. To keep it short, essentially what happens is that when i use the search bar in journey mode, none of the items get filtered. Even worse, whenever I try to switch to another tab without deleting the search bar text, my camera gets locked and the menu spazzes out. I'll include a video below of the results as well as recreating the incident.

https://github.com/DominicKarma/InfernumModePublic/assets/74155195/38a5436f-0a51-4b27-972f-7aec96655bab

Github wont let me post my Json in this ticket, so here are the mods that I run in my installation. My apologies if one of these mods is known for incompatibility and I was simply ignorant:
[
  "AlchemistNPCLite",
  "Antisocial",
  "AutoReroll",
  "BossChecklist",
  "Census",
  "CheatSheet",
  "DBZMODPORT",
  "DisableCorruptionSpread",
  "SerousCommonLib",
  "FriendlyNpcsDontDie",
  "GravityDontFlipScreen",
  "MagicStorage",
  "NoFishingQuests",
  "NoPylonRestrictions",
  "OreExcavator",
  "RecipeBrowser",
  "ShoeSlot",
  "ShopExpander",
  "WingSlotExtra",
  "WMITF",
  "AutoTrash",
  "CalamityFly",
  "CalamityModMusic",
  "Fargowiltas",
  "CalamityMod",
  "TooManySlots",
  "DBZGoatLib",
  "ChangeSleepTime",
  "miningcracks_take_on_luiafk",
  "FargowiltasSouls",
  "ItemMagnetPro",
  "DisableShopConditions",
  "CraftEveryWeapon",
  "FargowiltasMusic",
  "imkSushisMod",
  "ImproveGame",
  "ZenithProgression",
  "FargoSeeds",
  "DBZModFMMStyleQOL",
  "InfernumMode",
  "SubworldLibrary",
  "HyperResearch",
  "GohanForms"
]

**Comment by zium1337** [comment]
#104
