### ISSUE TITLE
Devourer of Gods keeps permanently disappearing [Bug]

### ISSUE THREAD

**Issue by The-Breadman22** [DominicKarma/InfernumModePublic#12]
The Devourer of Gods will go into his portal for a phase transition and never return. The fight doesn't end and I'm forced to close the game. It's happened a dozen or so times, but here are three clips (I uploaded them to youtube cause even a 17 second video is 3 times the size limit). 
https://youtu.be/sCG4EWCdbxM
https://youtu.be/lZp69c_DFUM
https://youtu.be/ETLo20TSk8E

Here is the client.log:
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12295015/client.log)

It's notable that it doesn't happen every time, but it happens enough that I'd like to figure out how to stop it. Thanks for any help you provide

**Comment by toasty599** [comment]
It is because he is going out of the world bounds, which breaks NPCs. I'll attempt to fix it, but that has already been tried multiple times already to clearly no avail. For the meantime, fight him away from the world border.
