### ISSUE TITLE
Crash with latest version of Fargos

### ISSUE THREAD

**Issue by JohnnyProxo** [DominicKarma/InfernumModePublic#121]
When loading the game after the 3.1.3 update of Fargos Mutant Mod, this crash appears
![image](https://github.com/DominicKarma/InfernumModePublic/assets/133610577/580b6e1c-62c1-4bbe-8632-527b301f5648)

**Comment by JohnnyProxo** [comment]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12679181/client.log)

**Comment by toasty599** [comment]
Fargo's will rollback their last update tomorrow to avoid breaking this.
