### ISSUE TITLE
infernum wont work crash engine

### ISSUE THREAD

**Issue by Ivis232** [DominicKarma/InfernumModePublic#123]
it wont load properly even paired with calamity world library and infer music 
![Screenshot 2023-09-21 204731](https://github.com/DominicKarma/InfernumModePublic/assets/145680242/85bfc5c6-8fd5-4076-96ad-4623206308a3)
![Screenshot 2023-09-21 204707](https://github.com/DominicKarma/InfernumModePublic/assets/145680242/de43bd2c-94e0-4866-b912-10ebd85005c9)

**Comment by DJBaphomet** [comment]
Experienced the same issue, it's on Fargo's end according to their discord, they're gonna have it fixed by tomorrow. For now there's a patch in their discord that fixes the issue until they get a proper hotfix put out on the workshop
