### ISSUE TITLE
providence keeps despawning in the arena when 2nd phase is reached (+ another bug)

### ISSUE THREAD

**Issue by terrahubrt** [DominicKarma/InfernumModePublic#126]
(BUG 1)

I accidentally destroyed the gate (specifically the texture) blocking access to the arena, and after defeating the Profaned Guardians, nothing happens, meaning I can't go to the arena to fight Providence.

(BUG 2)

When fighting Providence in another world where I have access to the arena, she despawns in the 2nd phase, even though she's not supposed to in the arena. I also spawn her in the arena, so I have no idea what's going on here.

These bugs are causing me to be softlocked in the game, as I can't exactly fight and defeat Providence like this.

**Comment by toasty599** [comment]
#90 beat her on death mode.
