### ISSUE TITLE
I don't really know how to phrase this but i think i got a massive code error

### ISSUE THREAD

**Issue by N44th44n** [DominicKarma/InfernumModePublic#127]
Here's an image of the error message
![unnamed](https://github.com/DominicKarma/InfernumModePublic/assets/145888960/de478f8d-6081-4033-8cc2-ff461dfcb8bd)

**Comment by N44th44n** [comment]
I forgot to mention I put the game on 1.4.3

**Comment by toasty599** [comment]
1.4.3 is not maintained any more. Use 1.4.4.
