### ISSUE TITLE
Storm weaver bricks the game in 1.4.4 Infernum

### ISSUE THREAD

**Issue by Luviam** [DominicKarma/InfernumModePublic#13]
During Storm Weaver's fight, the game completely freezes and is still frozen after restarting Tmodloader and reloading the world. Even if all other mods besides Calamity, SubWordLib, and Infernum are disabled. 

https://github.com/DominicKarma/InfernumModePublic/assets/56097409/7947040a-588a-42b2-a298-cd5f2982a80e

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12299797/client.log)

**Comment by toasty599** [comment]
This is fixed for the upcoming patch :)
