### ISSUE TITLE
Weird results and possible lag caused by interaction with Fargo's souls mod and Secrets of the Shadows mod

### ISSUE THREAD

**Issue by PeredurSaruin** [DominicKarma/InfernumModePublic#130]
**I have a modpack and some weird things are happening between the mods Sots, Calamity and Fargo's souls mod, mainly in its mode Eternity Mode.**

Mod list:
Calamity
Calamity Infernum mode
Fargos's Mutant mod
Fargo's Souls mod
Secrets of the Shadows

1 - When I activate Eternity mode from Fargo's Souls mod, void-like wall spheres from SotS starts to span spawn that kinda limit the player's moviment. That's not even the problem, the problem is the lag that this interaction is causing in my PC and my "huge" modpack. 

2 - I tested removing and adding mods one by one and got the following results:

- When Eternity mode is activated without Calamity Infernum mode solves the problem

   //I know that Eternity mode, Master mode and Infernum isn't supposed to works together, but:

- When Eternity mode is activated without SotS solves the problem

  //The problem is solved but I don't want to give up on **SotS** neither Infernum :(

**I talked with SotS dev and he said:** 
_The void like spheres spawning are an intentional gameplay mechanic, but they should only spawn once every couple of minutes and should stay spawned in, then some mod is causing an NPC in the world to despawn when it shouldn't, basically the spheres are tied to the Archaeologist NPC which spawns and respawns every about 10 minutes in SOTS. I don't think I can fix this since I believe it is on either infernum or fargos side there's no error so whatever is despawning the archaeologist is doing so intentionally (as in, it is being despawned for a reason, not because of a exception forcing it to despawn).
_

There's no errors in the client.log about this. I know Infernum and Eternity mode isn't supposed to work together, but I'm here to suffer xD. 

I really want to get rid of this error to use these mods together, love you all dev team ♥.

https://github.com/DominicKarma/InfernumModePublic/assets/145208192/559c2570-c976-40d1-812d-01aac92bf5cd

**Comment by VortexOfRainbows** [comment]
To clarify. I believe what is causing the error is a premature despawning of an NPC from SOTS. The question to ask would be: does Infernum have functions that globally despawn certain NPCs, and what is the criteria for the despawn if it exists?

**Comment by TheGrandQuest** [comment]
the issue is caused by eternity mode with infernum by itself causing no npcs to spawn theres no intended cross mod support with infernum and eternity as stated here #120
