### ISSUE TITLE
Profaned Garden not generating properly

### ISSUE THREAD

**Issue by GeaRetteX** [DominicKarma/InfernumModePublic#131]
Hi, just went to the underworld and noticed there was no profaned garden on the far right side of the map, but i noticed it partiatly started to generate, then got overwritten by the Brimstone Crag, is this normal?

![imagen_2023-09-28_015422295](https://github.com/DominicKarma/InfernumModePublic/assets/80774644/f698b02b-7797-4086-93c9-3817fdc41a20)

**Comment by toasty599** [comment]
Don't use any worldgen mods.
