### ISSUE TITLE
Moon lord can't be defeat

### ISSUE THREAD

**Issue by Fishbubu** [DominicKarma/InfernumModePublic#15]
In multplayer moon load can't be defeat.
Server not crashing no show anything.
Shade says it looks like multiplayer desyncs.
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12309025/client.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12309027/server.log)

**Comment by Fishbubu** [comment]
https://github.com/DominicKarma/InfernumModePublic/assets/141898712/83294c96-9e0b-4e18-a4b7-7234f775b2a6

Attach this problem video.

**Comment by Fishbubu** [comment]
Update:I trun off the Infernum mod the moon lord can be defeat.

**Comment by toasty599** [comment]
This is multiplayer desync, we cannot do much more than we already have to fix it unfortunately.
