### ISSUE TITLE
Hard crash during world load

### ISSUE THREAD

**Issue by Geckoleon** [DominicKarma/InfernumModePublic#18]
On one hand, the recent update did stop the game from failing to load the world with the sakura blossom error so that's nice
On the other hand, it instead now hard crashes to desktop either during load or as soon as the world loads
As far as I can figure out, if I try to enter the world right after booting up tmod, it'll crash at "loading world 100%", but if I first enter another world that works, it'll instead crash on the first frame of having the world loaded in
The world crash is on a world that was having the sakura error before, loading the same character onto a world that didn't have the sakura error works fine. I'm not sure if the fix requires a new world so if it does ignore this
Disabling this mod allows the world to load without error, so it does appear to be related to this, no clue how though
I'll include the logs but I'm unsure of how useful it'll be since at a quick glance there's no errors at the end of the log
[1st frame crash](https://github.com/DominicKarma/InfernumModePublic/files/12316120/client.log)
[during world load crash](https://github.com/DominicKarma/InfernumModePublic/files/12316177/client.log)

**Comment by toasty599** [comment]
Should hopefully actually be fixed now. Ditched the old obtainment method that led to this crash so will no longer occure.
