### ISSUE TITLE
Infernum Plantera 2nd phase little snachers not disappearing

### ISSUE THREAD

**Issue by kittyTechnician** [DominicKarma/InfernumModePublic#19]
During Planteras 2nd phase when she does the "extending vines" attack, the little snatchers come back and chase the player.
This is shown in the two images.

If this is intended then I am sorry, but from what I've seen and read, this didn't happen before 1.4.4 port.

![20230810235459_1](https://github.com/DominicKarma/InfernumModePublic/assets/82870327/0e984ea4-83f2-426b-bcfd-b6d15fe69c76)

![20230810235501_1](https://github.com/DominicKarma/InfernumModePublic/assets/82870327/2861defd-43fb-472c-8082-b07cb0004eff)

**Comment by toasty599** [comment]
Send your log file.

**Comment by kittyTechnician** [comment]
Do you mean this file?
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12320089/client.log)

**Comment by toasty599** [comment]
![image](https://github.com/DominicKarma/InfernumModePublic/assets/74939552/12578189-1bc0-4ebf-baa1-930b005b31a9)
Your Infernum is several versions out of date. Delete the version in your Mods folder and reinstall the mod, this has been fixed for a few versions now.
