### ISSUE TITLE
Moonlord's eyes don't want to die in multiplayer. (Never leaving first phase)

### ISSUE THREAD

**Issue by Gargule** [DominicKarma/InfernumModePublic#21]
It's just it. On a server, even when i'm the only player, Moonlord's eyes cannot be damaged beyond certain point. It still takes damage, but only plays "dying" animation for a second when hit. In singleplayer all works as intended. This bug may also affect some post-moonlord bosses as well. (We noticed strange behavior of profaned guardians as well, but we didn't killed them yet)
To reproduce just start multiplayer via "Host and play" button and then try to beat Moonlord in Infernum mode.
Don't think that logs or screenshots will help, but i'll provide both.
(Cannot remember how to attach labels here, sorry)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12318281/server.log)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12318282/client.log)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/30858121/05cd8952-3b5b-4034-82b1-91d545896af5)
UPD: Seems like it's #15 again. Unfortunately. What exactly causes this kind of bugs in mods? (Just curious because it's seems to be unfixable in every mod that have it)

**Comment by toasty599** [comment]
Terraria netcode is pretty poor.
