### ISSUE TITLE
Every boss after Moon Lord (Including Moon Lord) crash in multiplayer

### ISSUE THREAD

**Issue by Xiarno** [DominicKarma/InfernumModePublic#22]
It seems that in multiplayer after Moon Lord and including Moon Lord, every following boss will make the player that is not hosting the game immediately crash upon summoning any boss. This also includes the empress of light.

**Comment by Gargule** [comment]
We don't have this problem in our playthrough. (But we have similar) Do you have extra content mod beyond Calamity and Infernum?

**Comment by Xiarno** [comment]
> We don't have this problem in our playthrough. (But we have similar) Do you have extra content mod beyond Calamity and Infernum?

Doesn't seem to matter anymore. Apparently, a recent update fixed it.
