### ISSUE TITLE
crash during adding content when loading tmod (bug(dont know how to add label)

### ISSUE THREAD

**Issue by victorzkai0** [DominicKarma/InfernumModePublic#23]
already tried uninstalling everything, only calamity, subworld library and infernum mode remain, when starting with only calamity and subworld there are no crashes, so its a infernum thing, no issues with any other mod besides infernum either, sorry if not really informative when bug reporting, english is not my first language, gonna anex the log and image now, or at least try
![infernum crash](https://github.com/DominicKarma/InfernumModePublic/assets/142074947/72341e4b-e8bd-4115-85d5-851ad9bac8f9)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12326637/client.log)

how do i add a label????

**Comment by toasty599** [comment]
Should have fixed it, it will be included whenever the mod next updates.
