### ISSUE TITLE
Infernum entirely breaks the built-in Terraria Capture system

### ISSUE THREAD

**Issue by Joryho7** [DominicKarma/InfernumModePublic#24]
While playing with Infernum (the mod) enabled on TModLoader, using the Snapshot feature of Capture with a big enough snapshot area will causing black bars to appear across the image, causing large chunks of the image to go missing. In the worst case scenario, it'll cut off almost the entire bottom half of the image with a black bar.
![Capture 2023-08-12 18_01_51](https://github.com/DominicKarma/InfernumModePublic/assets/100448626/4d91eb08-00f5-4235-91db-4eb23e4e6217) Without Infernum enabled
![Capture 2023-08-12 18_07_24](https://github.com/DominicKarma/InfernumModePublic/assets/100448626/2f215319-ecd9-4c30-9ae5-812d4ec8a7aa) With Infernum Enabled

I assume this is because Infernum messes with the lighting engine in some way, likely caused by flashy effects from bosses such as Providence and the Greater Eidolon Wyrm.

**Comment by Joryho7** [comment]
Sidenote: I cannot physically add the "Bug" label to this issue.

**Comment by toasty599** [comment]
This will be very annoying to find the source of and fix, I cannot guarantee it will be resolved any time soon.
