### ISSUE TITLE
End of Credits crashing the game

### ISSUE THREAD

**Issue by JackFrtruck** [DominicKarma/InfernumModePublic#25]
![image](https://github.com/DominicKarma/InfernumModePublic/assets/142154803/82c8275d-94b9-449d-8336-417d953f6ad4)
**That's the crash error, it seems to be Infernum.**
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12329481/client.log)
[environment.log](https://github.com/DominicKarma/InfernumModePublic/files/12329482/environment.log)
[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12329483/environment-client.log)
[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12329484/Launch.log)
[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12329485/Natives.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12329486/server.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12329487/terrariasteamclient.log)
**These are the logs, if those help.**
**Anyway, I'm able to get through most of the credits, but it crashes every time I get to a certain point.**

**Comment by JackFrtruck** [comment]
Sorry if I left something out, I hardly know what I'm doing. If you need anything more, just ask, I'll do my best to get it to you.

**Comment by toasty599** [comment]
Don't worry about the labels, I don't think you can actually add them yourself which I did not know :p

**Comment by toasty599** [comment]
OK, this seems to be because one of the files does not match the capitalization of the others... Will be fixed for the next update.
