### ISSUE TITLE
Game freezes while dealing damage to Argus, the Bereft Vassal in multiplayer, additionally mod spawns like 25 of them at the same time

### ISSUE THREAD

**Issue by Maroy61** [DominicKarma/InfernumModePublic#27]
[server2.log](https://github.com/DominicKarma/InfernumModePublic/files/12329693/server2.log)

**Comment by Maroy61** [comment]
![image](https://github.com/DominicKarma/InfernumModePublic/assets/58446318/45894cc8-6d92-4eda-b016-de4d44087983)
![2023-08-13_17-02-01](https://github.com/DominicKarma/InfernumModePublic/assets/58446318/d8ad747c-95cd-4985-968f-cdfea7dee36a)
![2023-08-13_17-11-32](https://github.com/DominicKarma/InfernumModePublic/assets/58446318/67ae2b68-9e4e-4726-bf88-14cb9d796070)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/58446318/5b7e882b-7c20-4382-8fa1-a8a6ae521ed6)

**Comment by votex09** [comment]
That fight doesn't even work for me in multiplayer, I can open the portal, but not go through it.  I'm surprised you made it that far!

**Comment by toasty599** [comment]
Should be fixed for next patch?
