### ISSUE TITLE
Crashing during boss fights and normal gameplay.

### ISSUE THREAD

**Issue by GearsawStudios** [DominicKarma/InfernumModePublic#28]
Mostly during bosses, submitting on behalf of my friend.
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12330900/client.log)

**Comment by toasty599** [comment]
This is unrelated to Infernum, I would recommend **not** using OneDrive as it tends to break things with tModLoader

**Comment by GearsawStudios** [comment]
> This is unrelated to Infernum, I would recommend **not** using OneDrive as it tends to break things with tModLoader

Thanks
