### ISSUE TITLE
Crash on Loading Screen Infernum in Calamity 2.0.3.2

### ISSUE THREAD

**Issue by GustronReal** [DominicKarma/InfernumModePublic#29]
When i try to play the game, the game gave me an error when try to load with calamity (the newest version 2.0.3.2)
![tmoderropr](https://github.com/DominicKarma/InfernumModePublic/assets/9908535/f8d09ce8-52a0-4119-8eeb-33556f082c2a)

Can you help me with that?

**Comment by Anthony0965** [comment]
I am getting that same issue too and I was just about to create an issue for it. Also I am using Subworld Library v2.2.1.2 which also seems to be the latest version.

Pressing Continue or Skip Loading Mods leads to this as well:
![20230814013005_1](https://github.com/DominicKarma/InfernumModePublic/assets/35509643/4b1cd88d-ae8f-4d37-a64b-70b468defdd5)

**Comment by jessefjxm** [comment]
Came up with same issue today

**Comment by toasty599** [comment]
Will fix ASAP after breakfast, its 8am currently.

**Comment by toasty599** [comment]
Patch has been published.
