### ISSUE TITLE
maintain git + patch notes please

### ISSUE THREAD

**Issue by blueperson2** [DominicKarma/InfernumModePublic#3]
this mod is fantastic but it seems this git is not maintained. can we please see patch notes or is there some mysterious spot to see them that most can't see. the discussions on the workshop page are locked so no info there, and this git is not updated so none here either.

for example, profaned guardians was pretty much unplayable in multiplayer then .17 and .18 rolled around and that seemed to fix a lot. or was that another mod doing something? i have no idea, there's no patch notes

old discord links such as on the tmodloader site and workshop page don't function. if that's intended or not i don't know, but if that's really the only location for proper patch notes then some line of text saying so would be nice

you've definitely had experience with how some players are incredibly stupid and don't understand things in the mod. like how subworlds don't have proper multiplayer support yet. perhaps you can add a summon description in boss checklist for argus that he is fought in a subworld and as such is singleplayer exclusive, or putting it somewhere on the workshop page

infernum is easily one of the best mods made when it comes to super fun bosses that push players to their limits. keep up your design philosophy, and don't sink into the suggestions of people who don't know design. you have made one of the greatest gaming experiences people can have. but please let us see patch notes

**Comment by toasty599** [comment]
This will be remedied going forwards, I will try to keep up to date patch notes and include each updates changelogs in a txt on this repo :)
