### ISSUE TITLE
Infernum cannot load after the latest update.

### ISSUE THREAD

**Issue by GoldMoon1033** [DominicKarma/InfernumModePublic#30]
Infernum cannot load when I open TModLoader. It give me these logs ![image](https://github.com/DominicKarma/InfernumModePublic/assets/102957192/9b889b30-d49e-4f6d-aa0f-c6488a11694b)

**Comment by Fl4m3thrower** [comment]
a patch was posted about 3 hours ago fixing it, version should be 1.9.27

**Comment by GoldMoon1033** [comment]
that was recently after the 1.9.27 update. I played the game before updating and have no issue before.

**Comment by WildberrySherbert** [comment]
It's not updating for me

**Comment by Fl4m3thrower** [comment]
one way to force the game to update mods is to delete them through manage mods and then resubscribe on the workshop or download from mod browser again

**Comment by WildberrySherbert** [comment]
That fixed it, thanks!

**Comment by Zora92337** [comment]
im having the same issue but with version 1.9.28
