### ISSUE TITLE
Cant summon boss infernum

### ISSUE THREAD

**Issue by HandAutistic** [DominicKarma/InfernumModePublic#31]
Can't summon Guardians 
![image](https://github.com/DominicKarma/InfernumModePublic/assets/48625864/aae91822-be6b-4318-b806-c3de01cc48af)
And providence doesn't have a second phase

**Comment by toasty599** [comment]
Logs? It needs to be day for guardians

**Comment by RexusOhm** [comment]
I have the same problem, the Guardians cannot be summoned at daytime or anytime.
![image](https://github.com/DominicKarma/InfernumModePublic/assets/59621106/696aef1a-6c13-4736-a8d3-3608a1a6fabf)
Error information is not displayed in the logs.


[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12387978/client.log)

**Comment by toasty599** [comment]
Read the text. You need to use the item on the cliff.

**Comment by toasty599** [comment]
#90
