### ISSUE TITLE
Softlock when using The Wayfinder when grappled onto a wall

### ISSUE THREAD

**Issue by Jatie1** [DominicKarma/InfernumModePublic#32]
Steps to replicate:

1. Grapple to the wall like this where there is a lot of space under you (like in a hellevator):
![image](https://github.com/DominicKarma/InfernumModePublic/assets/70575943/2b535876-9b0c-4b74-bbd6-d82c2e4b491f)
2. Create the wayfinder portal in this position
3. Teleport to the portal

You will end up softlocked like this in the middle of nowhere, can't even pause the game to exit:
![image](https://github.com/DominicKarma/InfernumModePublic/assets/70575943/182d7285-85a2-4154-b48b-0990f3572145)

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12336198/client.log)

**Comment by toasty599** [comment]
Fixed for next patch.
