### ISSUE TITLE
Asset could not be found: "Content\Items\ElysianRose"

### ISSUE THREAD

**Issue by Jatie1** [DominicKarma/InfernumModePublic#33]
Got this error pop-up when entering the Profaned Garden for the first time

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12336387/client.log)

**Comment by Va-ki** [comment]
I am encountering the same issue here.
The tablet in this Profaned Garden also disappears a millisecond after rendering, making reading impossible.

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12339136/client.log)

**Comment by toasty599** [comment]
Fixed for next patch.
