### ISSUE TITLE
Very easy and accidental item duplication

### ISSUE THREAD

**Issue by Rolianoob** [DominicKarma/InfernumModePublic#35]
If you use "Quick stack to nearby chests" the items in your inventory will stay there and appear in the chest. We discovered this bug on 2023.08.14.

**Comment by toasty599** [comment]
Is this even an infernum issue

**Comment by Rolianoob** [comment]
Not sure, it is our first infernum world and we never had this bug before,
so we think it is infernum related. We discovered this bug in the first 10
minutes of the playthrough.

Toasty ***@***.***> ezt írta (időpont: 2023. aug. 15., K,
14:13):
