### ISSUE TITLE
Infernum providence laser show an image before actually attack

### ISSUE THREAD

**Issue by Deserf** [DominicKarma/InfernumModePublic#36]
I cant dodge the laser because its didnt have an image before it actually shoot laser I post video of it, ignore the sound 

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12337371/client.log)
[environment.log](https://github.com/DominicKarma/InfernumModePublic/files/12337372/environment.log)
[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12337373/environment-client.log)
[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12337374/Launch.log)
[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12337375/Natives.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/fi

https://github.com/DominicKarma/InfernumModePublic/assets/142250074/56736c4b-94e6-4d07-9eaa-521cf622ecb9

les/12337376/server.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12337377/terrariasteamclient.log)

https://github.com/DominicKarma/InfernumModePublic/assets/142250074/8d90bba1-6b2f-4d91-a238-9ec80fe38645

**Comment by toasty599** [comment]
Fixed for next patch.
