### ISSUE TITLE
Empress of Light lance projectiles being invisible along with its telegraph

### ISSUE THREAD

**Issue by Optrixxx** [DominicKarma/InfernumModePublic#39]
I was prepping to fight EoL when I started and couldn't see the lances attack

https://github.com/DominicKarma/InfernumModePublic/assets/142260283/4f880dff-67d8-45c4-9c31-b3e7f0d6d62b

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12338627/client.log)

**Comment by Optrixxx** [comment]
This also applies to Artemis lacking any visuals for the tracking laser spam attack, the initial telegraph is fine but the lasers do not appear.

**Comment by toasty599** [comment]
Fixed for next patch.
