### ISSUE TITLE
Mod wont load

### ISSUE THREAD

**Issue by RetroArkGames** [DominicKarma/InfernumModePublic#40]
![20230814121014_1](https://github.com/DominicKarma/InfernumModePublic/assets/142263270/d921f3fc-a77f-46ac-8b4c-b46f9c9c2269)
![20230814121021_1](https://github.com/DominicKarma/InfernumModePublic/assets/142263270/992bb32c-e829-425f-9b8d-e6e9b2d35d4e)

i dont know why it wont load or what is causing it  here is the collection of mods im using https://steamcommunity.com/sharedfiles/filedetails/?id=3020206120

**Comment by RionWillians** [comment]
It's happening to me as well, the mod gotta be updated

**Comment by PoisonousNut** [comment]
They have already put out a patch for this issue. Try updating your mods. If that doesn't work, try forcing your mod browser to do so. Uninstall the calamity Infernum mod via the mod browser. Then, re-download it. That should force T-mod loader to update the mod, and SHOULD fix the issue. If it does not fix the issue, then you will need to wait for them to update the mod.

**Comment by toasty599** [comment]
You do not have the correct mod version.
