### ISSUE TITLE
Intense Lag Despite (AFAIK) Meeting System Recommendations

### ISSUE THREAD

**Issue by lunalunja** [DominicKarma/InfernumModePublic#42]
Ryzen 5 2600 Six Core | RTX 3060 12GB | 16GB ram

I'm unsure if it's a conflict with certain mods, but I've tried messing with the config as much as possible to fix the lag but nothing has been working. I used to lag slightly with the Light and Shadows mod so I disabled it, but that somehow made it worse(?) Going into places like Infernum's Abyss, the Sunken Sea, and even Providence's arena is where the lag spikes the most (outside of boss fights, which are a whole nother story). When in normal gameplay (In normal forest biome, for example)  it reaches 60 fps regularly and then immediately dips down to 50-55, and sometimes even less than 40. The lag never results in a crash no matter how severe it gets, so I don't have any error messages I can work with to try and find the issue. Also, I noticed while recording that a weird black bar appeared on the bottom of my screen for some reason. 

**v v CONFIG/MODS v v**
https://github.com/DominicKarma/InfernumModePublic/assets/138081961/35882b05-61ae-4c55-a109-fc46f416d098

**v v LAG ON STARTUP/IN NORMAL GAMEPLAY v v**
https://github.com/DominicKarma/InfernumModePublic/assets/138081961/d74570ee-219b-407e-a73f-947cd2164f0c

**v v LAG IN SULPHUROUS SEA v v**
https://github.com/DominicKarma/InfernumModePublic/assets/138081961/067e297a-f46e-4d4f-bc74-908a15ab95ef

**Comment by ettestech** [comment]
The "lights and shadows" mod makes the lighting process run on the GPU instead of the CPU, which results in a slight improvement in the game's FPS. That's why when you deactivate it, you experience a loss in FPS. I also have the same lag in those areas :/

**Comment by toasty599** [comment]
That is false, lights and shadows does no such thing. Fancy Lighting is the mod that changes the lighting process.
Check if this happens with only Infernum and its dependencies please

**Comment by lunalunja** [comment]
@toasty599 
I only lag with Infernum installed and is the only mod that has generally made me lag as consistently as it does. Even Calamity on its own doesn’t do this, and Subworld Library isn’t the issue since I’ve run mods that require it in the past with no problems

**Comment by ettestech** [comment]
> That is false, lights and shadows does no such thing. Fancy Lighting is the mod that changes the lighting process. Check if this happens with only Infernum and its dependencies please

I didn't know that about the lights and shadows mod, sorry for the incorrect statement.

**Comment by votex09** [comment]
You should try the Cryogen fight.  For me its 2 fps.
I'm curious how it is for you.

**Comment by lunalunja** [comment]
@votex09 
Cryogen was like 45ish fps consistently except for a few attacks with a lot of projectiles. It’s pretty tame compared to some other bosses like The Twins which lagged quite a lot, and Plantera is quite literally unplayable for me so I stopped there until I can get this fixed.

**Comment by votex09** [comment]
Strange.  Maybe it's a Linux thing.  Twins and Plantera were "fine" for me.  Definitely not 60fps though.  Haven't tried any boss before Profaned Guardians - since no one can get them to spawn at the moment.

Plaguenades (Rogue weapon) micro freezes the game for me as well; as a side note.

**Comment by lunalunja** [comment]
@votex09 
Interesting. Infernum’s performance has always puzzled me since I’ve had multiple friends with worse pc specs than me run it completely fine. Running it literally just by itself and it’s dependencies doesn’t help, so it’s definitely not a mod conflict I don’t think.

**Comment by RussellMMO** [comment]
Not a guaranteed fix, but if you have the boss checklist mod enabled, disable that. It's been having massive frame rate issues with other mods, and the steam comment section is also full of people having the same issue.

**Comment by RussellMMO** [comment]
Try disabling boss checklist @lunalunja , that mod has been having some issues lately and disabling that mod brought me from 40fps when fighting a boss to almost a smooth 60fps. Not sure why this mod is doing this, but I'm not alone in it. Their comment section in the steam workshop is full of similar issues. Hopefully this helps

**Comment by toasty599** [comment]
You have a lot of mods, disabling several of them will likely help. Performance issues with certain things will be looked into in future.
