### ISSUE TITLE
Missing projectiles and telegraphing signs

### ISSUE THREAD

**Issue by BearDrillz** [DominicKarma/InfernumModePublic#43]
Invisible projectiles noticed on Empess of Light (swords at the beginning), Yharon's fiery dashes can't be seen as well, numerous invisible projectiles on exo-mechs and also no Wayfinder white flashing effect on teleportation

Probably way more projectiles may be broken with different bosses

[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12339827/Launch.log)
[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12339828/Natives.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12339829/terrariasteamclient.log)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12339830/client.log)
[environment.log](https://github.com/DominicKarma/InfernumModePublic/files/12339831/environment.log)
[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12339832/environment-client.log)

**Comment by BearDrillz** [comment]
Probably a better log recorded after witnessing all issues mentioned in the message above

[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12342170/environment-client.log)
[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12342171/Launch.log)
[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12342172/Natives.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12342173/terrariasteamclient.log)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12342175/client.log)
[environment.log](https://github.com/DominicKarma/InfernumModePublic/files/12342176/environment.log)

**Comment by toasty599** [comment]
Fixed for next patch.
