### ISSUE TITLE
Dreadnautilus not listed in Boss Checklist mod as a Boss/Miniboss.

### ISSUE THREAD

**Issue by PlayfulPiano** [DominicKarma/InfernumModePublic#44]
Fairly straightforward issue here, but the revamp to Dreadnautilus to act as a proper boss doesn't have it listed as such (or miniboss due to the lack of a treasure bag) within the Boss Checklist mod. I'm unsure where exactly the boss should be placed in terms of game phase within HM, but i'd assume pre-queen slime.
![image](https://github.com/DominicKarma/InfernumModePublic/assets/3158887/9ebe086d-78a2-4613-90ce-58d936a4dfaf)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/3158887/40632842-2410-4bc0-bd9c-3676c8c39aba)

**Comment by toasty599** [comment]
TBH I wouldn't class it a boss even with the rework to improve the fight and title card. I will add it if I have time though.
