### ISSUE TITLE
Knowledge Bereft Vassal's tooltip issue

### ISSUE THREAD

**Issue by minejango2** [DominicKarma/InfernumModePublic#47]
https://github.com/DominicKarma/InfernumModePublic/assets/56389468/8e55a169-8116-441d-bb9f-32acdd62289d

As in the video, the lore that comes out when you originally press the Shift key is visible from the beginning, and when you press the Shift key, the context value is displayed.

Mod list:
Calamity Mod v2.0.3.2
Calamity Mod Music v2.0.3.1
Infernum Mode v1.9.27
Cheet Sheet v0.7.4.9

(This issue has been present since the 1.4.4 port.)

(This article was written using a translator. I'm really sorry if my post has caused any inconvenience)

**Comment by toasty599** [comment]
Fixed for next patch.
