### ISSUE TITLE
Infernum mode not "loading properly" after loading mods after tmodloader bootup

### ISSUE THREAD

**Issue by th3hatman** [DominicKarma/InfernumModePublic#48]
So, I was playing tmod in 1.4.3 and I decided to port to 1.4.4 and upon loading in the mods I got hit with an error according infernum about stuff not being ported despite it being ported, and it didn't happen in 1.4.3 but I was on the legacy branch for about 1 month before the transition here are some images: 
<img width="1532" alt="Screenshot 2023-08-15 185253" src="https://github.com/DominicKarma/InfernumModePublic/assets/142302932/3b46eec7-7a39-4a6b-a768-2d255022a68e">

<img width="1514" alt="image" src="https://github.com/DominicKarma/InfernumModePublic/assets/142302932/1faa8026-f9f1-4fae-836b-06ae81889345">

Modlist:
Calamity mod
Calamity mod music
Luiafk reborn
Census
Biome titles
Vanilla calamity mod music
Calamity interludes
Deimos
Loot beams
Grav portions don't flip
Smarter cursor
Infernum patch
Magic storage
Infernum mode
Infernum music
Multi lures
Absolute 
Subworld
Calamity flamethrowers
Better zoom
Concise mod list
Terraraa ambience api
Terraria ambience
Structure helper
Alc npc lite
Calamity rarities 
Noxus
Wikithis
Dialogue patch
Particle library
Boss checklist
Improved movement visuals
Atmospheric torches 
Recipe browser
Colored calamity relics
Luiafk reborn
Ore Excavator 
Fargo's mutant
Calamity vanities 
Better expert rarity 
Hero’s mod 
Cheat sheet
Auto trash
Light and shadows 
Wings slot extra
Begone evil
Fargo's best of both worlds
Better blending
Calamity Item swap
Weaponout
Some help would be great!

**Comment by th3hatman** [comment]
I've seen some of the patches but tmod wont update all mods without crashing I can try unsubscribing deleting the mods and getting them back again, bit it didn't work either. Time will tell I guess

**Comment by th3hatman** [comment]
Now that I fixed it for one time, all my save files deleted themselves and sent me back to mechs and updated my files a month back and deleted everything up to this date, anybody get that issue?

**Comment by toasty599** [comment]
You need to install the correct mod.
https://steamcommunity.com/sharedfiles/filedetails/?id=3015412343
