### ISSUE TITLE
Ceaseless void background doesn't fill screen in 1920x1080

### ISSUE THREAD

**Issue by FoxChanHelpful** [DominicKarma/InfernumModePublic#49]
Not sure if this has already been addressed but the background during the ceaseless void fight doesn't fill the screen when playing in a resolution other than 3840x2160 (4k) 

![image_2023-08-15_061155070](https://github.com/DominicKarma/InfernumModePublic/assets/72468609/4c0cad00-5255-4073-84b4-d09ea2940a2e)

**Comment by toasty599** [comment]
Going into windowed mode fixes this, it does not work in fullscreen.
