### ISSUE TITLE
Game crashes after update

### ISSUE THREAD

**Issue by FireDemon616** [DominicKarma/InfernumModePublic#50]
![image](https://github.com/DominicKarma/InfernumModePublic/assets/101921296/c706a716-ef69-4676-a864-70b37f839a9b)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/101921296/f5fd1251-689e-45cf-839f-91c26e34ae39)

**Comment by Stachelbeere1248** [comment]
calamity updated but the infernum addon auto-update glitched (afaik due to ownership transfer on steam workshop)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/59412936/f3d41425-9012-4899-a7a8-eb748ec245c5)
