### ISSUE TITLE
Certain assets not loading 

### ISSUE THREAD

**Issue by SwitchUser2** [DominicKarma/InfernumModePublic#51]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12352886/client.log)
assets such as, the white flash when teleporting with wayfinder, profaned guardian beam indicator line during first phase, and elysian rose not loading. I only get an error for the elysian rose not loading. There may be more but have not looked.

Running Tmodloader v2023.6.25.31

Modlist consisting of:
Calamity v2.0.3.2
Infernum v1.9.27
Subworld Library v2.2.1.2
![Screenshot 2023-08-15 162009](https://github.com/DominicKarma/InfernumModePublic/assets/142352160/5d5c72bc-8cb4-43de-b73e-ce1771bc481c)

**Comment by SwitchUser2** [comment]
I just didnt update infernum, was unaware.

**Comment by toasty599** [comment]
Update your mod.
