### ISSUE TITLE
Invincible Moon Lord (Multiplayer)

### ISSUE THREAD

**Issue by NeEba4** [DominicKarma/InfernumModePublic#53]
Well. Tried to beat moonlord with some friends and it went wrong. Cant kill both hands and head. Plus the circular laser attack just bugged (blind or not synchronized).

https://github.com/DominicKarma/InfernumModePublic/assets/142412366/7d0ce05f-5017-4dc2-873d-7a446fc0eea8

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12359727/client.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12359732/server.log)

**Comment by votex09** [comment]
Same happens to me - except also in Singleplayer.
I don't this this is isolated to Multiplayer only as I've tried both ways.

**Comment by Stachelbeere1248** [comment]
I have the same issue

**Comment by noxlock** [comment]
also getting this..
