### ISSUE TITLE
Multiple issues with the Profaned boss fights

### ISSUE THREAD

**Issue by NeuTraLZero** [DominicKarma/InfernumModePublic#54]
happen on version 1.9.28

1. The Profaned Guardians won't spawn at all even if it's day time
![image](https://github.com/DominicKarma/InfernumModePublic/assets/43245485/52ecea73-cdfb-4d84-a71d-d7cb5788fbd5)
2. The note in the middle of the garden comes up for a split second then closes itself
![image](https://github.com/DominicKarma/InfernumModePublic/assets/43245485/6fe31137-4cbf-413b-9202-030e3841570d)
3. Error message popping up the first time when Providence uses the crystal attack, the crystals are also invisible but still have telegraph
![image](https://github.com/DominicKarma/InfernumModePublic/assets/43245485/1b36602d-b36f-4cbb-909b-0accd62dec1e)
4. Providence despawns when entering her second phase
![image](https://github.com/DominicKarma/InfernumModePublic/assets/43245485/69c2a0ab-306c-476d-9e2b-6c49200b6f74)

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12360404/client.log)

**Comment by suy3** [comment]
This happens with me tok

**Comment by GourmetTinCan** [comment]
Same thing here. Something to add though; trying to troubleshoot for myself I force spawned them in using Hero's Mod. When you spawn in the Commander, the Healer and Defender actually spawn up in the top left corner of the map.
![1](https://github.com/DominicKarma/InfernumModePublic/assets/34245683/
e810f05a-85d8-4fe2-87a3-8bba8073a6dd)
If you try to get near the area they are, you get teleported outside of the map (therefor you can't move). The initial attack before you break down the wall is happening up here too.
![2](https://github.com/DominicKarma/InfernumModePublic/assets/34245683/b7be1a67-f5bc-46c2-b2d9-1172ac9104db)
Spawning in more Healers and Defenders makes them flee to the top left with the others
![3](https://github.com/DominicKarma/InfernumModePublic/assets/34245683/c2479dae-73ae-4c50-996a-cd8ece105287)

Not really sure if this helps fix the bug(s) at all, but just in case.

**Comment by Geckoleon** [comment]
I'm getting the same issue, and the log doesn't have any errors or anything either

**Comment by toasty599** [comment]
Should be resolved for next patch

**Comment by Alexander1811** [comment]
When would the next patch be available?
