### ISSUE TITLE
i can't load the mod

### ISSUE THREAD

**Issue by sans123234** [DominicKarma/InfernumModePublic#55]
every time i try to load infernum (with calamity v2.0.3.2 and with subworld library v2.2.1.2) this message appears
![Captura de tela 2023-08-16 141132](https://github.com/DominicKarma/InfernumModePublic/assets/142436932/ec63a53f-4d4e-4b6a-a6fc-813b96299ee6)
as you can see im in infernum v1.9.24 and i cant update it nor downgrade calamity mod, please i need to play this mod

**Comment by Zora92337** [comment]
i have the same issue

**Comment by sans123234** [comment]
oh, it worked

**Comment by sans123234** [comment]
i dont know why i didnt think that, but what exactly is your problem?

**Comment by Zora92337** [comment]
i have the exact same issue as you did but i cant update it aswell since im already using the newest version
