### ISSUE TITLE
mod doesnt enable

### ISSUE THREAD

**Issue by Zora92337** [DominicKarma/InfernumModePublic#56]
I just downloaded the infernum mode mod with all the dependencies but when i clicked on "back" after enabling the mod, it disabled it again

**Comment by Zora92337** [comment]
heres a screenshot of the log
![image](https://github.com/DominicKarma/InfernumModePublic/assets/84603098/ff462eed-6d53-4742-9ff8-f43bb7610961)

**Comment by cbas879** [comment]
so im having this issue too and updating it didnt do anything

**Comment by mariohero24** [comment]
> Update your calamity

calamity is fully updated, and i am having the same issue

**Comment by Zora92337** [comment]
what is the newest version? as you can see on the screenshot, i possess version 1.9.28 but i just downloaded it shortly before i opened this issue

**Comment by Zora92337** [comment]
> Update your calamity

it worked tysm i downloaded calamity ONE DAY before the newest update XD
