### ISSUE TITLE
DoG doesn't work in multiplayer anymore :(

### ISSUE THREAD

**Issue by ZapGamer** [DominicKarma/InfernumModePublic#58]
The video file was too big so here's the youtube link:
(sorry for no audio)
[https://www.youtube.com/watch?v=h3z2V0kZmzA](https://www.youtube.com/watch?v=h3z2V0kZmzA)

**Comment by ZapGamer** [comment]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12369385/client.log)
[server.log](https://github.com/DominicKarma/InfernumModePublic/files/12369386/server.log)

here are the logs if you need them

**Comment by toasty599** [comment]
Should be resolved for next patch
