### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Legeboka** [DominicKarma/InfernumModePublic#59]
Game crashes when summoning a Brimstone Elemental. 
[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12380728/Natives.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12380729/terrariasteamclient.log)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12380730/client.log)
[environment.log](https://github.com/DominicKarma/InfernumModePublic/files/12380731/environment.log)
[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12380732/environment-client.log)
[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12380733/Launch.log)

**Comment by toasty599** [comment]
Pay attention to the in-game message when joining a world.
