### ISSUE TITLE
Sharkrons are not dying/despawning

### ISSUE THREAD

**Issue by EdenZero0** [DominicKarma/InfernumModePublic#63]
Sharkrons summoned by infernum duke are not dying/despawning on contact with blocks and platforms. They remain in place on the block or platform they contacted with 0 AI and do not despawn when the fight is over either.
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12385876/client.log)

**Comment by toasty599** [comment]
Fixed for next patch.
