### ISSUE TITLE
EoW vanilla boss bar broken

### ISSUE THREAD

**Issue by AVoidKnight** [DominicKarma/InfernumModePublic#64]
![20230817172918_1](https://github.com/DominicKarma/InfernumModePublic/assets/136589540/e66b599d-935c-4816-ac5d-799effc9458f)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/136589540/3af1ddc7-33d3-4940-98f8-e5d5f33fcc7b)
![image](https://github.com/DominicKarma/InfernumModePublic/assets/136589540/ba62548c-8608-45b9-9621-60c85f1f8d17)

**Comment by toasty599** [comment]
Not sure why that is happening, but you can use the calamity or Infernum boss bars to "solve" this issue.
