### ISSUE TITLE
Credits are crashing after scal and exo mechs have been defeated

### ISSUE THREAD

**Issue by Sneaks103** [DominicKarma/InfernumModePublic#65]
![Screenshot 2023-08-17 205219](https://github.com/DominicKarma/InfernumModePublic/assets/142728549/969eb2f6-8be3-47b9-b789-ac19392c33aa)
![Screenshot 2023-08-17 205203](https://github.com/DominicKarma/InfernumModePublic/assets/142728549/43dce7a1-5caa-4b62-aafe-9e9ad061eff5)

**Comment by toasty599** [comment]
Fixed for next patch.
