### ISSUE TITLE
Lots of crashes

### ISSUE THREAD

**Issue by PlsStandbyMe** [DominicKarma/InfernumModePublic#67]
Both Calamity music and/or infernum music causes the game to crash when some bosses spawn, so far those are: Queen bee, Plantera, Brimstone elemental, Duke fishron, Moon Lord, Profaned guardians and Providence. Also, I can't read the sign on the middle of the profaned garden, and, apparently, using  a insta-bridge from LuiAFK makes it impossible to spawn the profaned guardians, wich soft-locks you out of the rest of the post-Moon_Lord content ( i tried in a new world and they spawned, wich made the game crash lol).

**Comment by toasty599** [comment]
Read the in-game message when joining a world? Should be fixed for next patch.
