### ISSUE TITLE
Calamity not loading with Infernum enabled

### ISSUE THREAD

**Issue by PikachuGabe** [DominicKarma/InfernumModePublic#68]
Calamity fails to load with Infernum enabled. Infernum version: 1.9.28 Calamity version: 2.0.3.2 Subworld Library version: 2.2.1.2 TModLoader version: 2023.6.25.31 Terraria version: 1.4.4.9
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12401624/client.log)
censored client log so I dont leak my name. relevant lines: 4102-4152(inclusive)

**Comment by toasty599** [comment]
The error is a calamity one, not infernum.
