### ISSUE TITLE
Game crashes when spawning Profaned Guardians/Providence

### ISSUE THREAD

**Issue by Wiserdis** [DominicKarma/InfernumModePublic#7]
When spawning Profaned Guardians or Providence, game crashes in both Singleplayer and Multiplayer in the 1.4.4.9 terraria version, 1.9.24 Infernum version, 2.0.3.1 Calamity version.
Server log doesn't seem to have much information about the crash, here is the crash excerpt:

**[10:50:29.584] [Server Loop Thread/INFO] [Network]: [0][127.0.0.1:62073 ({Player Name})] Terminating: Connection lost
[10:50:29.584] [Server Loop Thread/INFO] [Network]: [0][127.0.0.1:62073 ({Player Name})] Closing TcpSocket
[10:50:29.585] [Server Loop Thread/INFO] [Terraria]: {Player Name} has left.
[10:50:29.585] [Server Loop Thread/INFO] [Terraria]: Local player left. Autoshutdown starting.
[10:50:29.809] [Main Thread/INFO] [StatusText]: Saving world data
[10:50:29.997] [Main Thread/INFO] [StatusText]: Validating world save**

Above this are some logs about Magic Storage which are unimportant.
Client.log for Singleplayer test seems to have even less information, with nothing beyond loading up the world and my character entering it.
Disabling all other mods except Infernum, Infernum Music, Calamity, Calamity Music, and Subworld Library did not have an effect on the issue. Disabling boss introduction animations did not have an effect of the issue (it didn't seem to even disable the introduction animations at all)
[*Showcase of the bug*](https://www.youtube.com/watch?v=THLTyeqaTlo)

Update: the same issue happens with at least Empress of Light, Scal, and exo mechs as well
Update 2: turning on Reduced Graphical Settings and turning off Screen Overlays, just turning off Screen Overlays, and just turning on Reduced Graphical Settings did not help [as well as RGS=on, SO=off, BIA=off] (tested on Scal) {I did notice that the red particles on Scal's spawn were really oversaturated, perhaps spawning in too many of them to cause the crash?}

**SOLVED: for some reason, music mods ruin these bosses. Turning off BOTH Calamity and Infernum music mods fixed the crashes, checked on all bosses mentioned above, I assume this will also work using the Soul Driven Headphones but it was not tested. I am not the only one having this issue, though [*this person*](https://www.reddit.com/r/CalamityMod/comments/14xigzp/infernum_supreme_calamitas_causes_my_game_to/) had it before 1.4.4, which I did not**

**Comment by toasty599** [comment]
This is known, and is being worked on.

**Comment by toasty599** [comment]
Ok, I must admit defeat with this one. It has started occurring to me too and I've tried about a million fixes to no avail. Im pretty sure its something specific to a PC, such as outdated drivers but that didnt lead anywhere. I will most likely end up removing the tracked music system that causes this crash, which will unfortunately remove all music syncing things from the mod. I don't like that, but I cannot find another solution.
