### ISSUE TITLE
Kevin seems to make the player glow while wearing Auric Tesla.

### ISSUE THREAD

**Issue by Beefaroni246890** [DominicKarma/InfernumModePublic#70]
Is this a feature? it doesn't seem intentional.
![20230822211530_1](https://github.com/DominicKarma/InfernumModePublic/assets/142954373/7de0243f-9d1c-47bd-ae47-41fc145e8526)
![20230822211532_1](https://github.com/DominicKarma/InfernumModePublic/assets/142954373/e4d11c43-ab83-41d1-ac08-764e770ebed0)

**Comment by Beefaroni246890** [comment]
I have already tried disabling all resource packs, I may be missremembering, but I think this only happened after installing Lights and shadow and improved lighting. Deleting those did not fix the problem, deleting and then reinstalling my mods also did nothing.

**Comment by Beefaroni246890** [comment]
Just realized I was wearing a CAL VAL vanity in the screenshots, this happens even without it equipped.

**Comment by toasty599** [comment]
This is a calamity bug.
