### ISSUE TITLE
I can't summon the profaned guardians

### ISSUE THREAD

**Issue by zerito1x** [DominicKarma/InfernumModePublic#71]
https://github.com/DominicKarma/InfernumModePublic/assets/142956409/4ef7335c-9d34-4c2e-b465-841b2441acb2

I can't summon the profaned guardians and neither can I read the sign in the middle of the shrine for some reason (I've already killed moon lord and dragonfolly) 
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12414503/client.log)

**Comment by Beefaroni246890** [comment]
You did use it at the edge of the cliffside like you are supposed to right?

**Comment by zerito1x** [comment]
> 

Yup I kept spamming my clicks

**Comment by zerito1x** [comment]
I fixed it by spawning it with cheat sheet but it went straight into second phase and when trying to fight providence, I get this error and providence just disappears (I've already checked the integrity like 3 times)
![imagen](https://github.com/DominicKarma/InfernumModePublic/assets/142956409/60da6b99-1575-4c70-a32e-f158a84e8371)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12416664/client.log)

**Comment by ziolek23** [comment]
https://github.com/DominicKarma/InfernumModePublic/issues/54
