### ISSUE TITLE
I can't into the subworlds, it get stuck at saving world data 100%

### ISSUE THREAD

**Issue by RodrigoMz14** [DominicKarma/InfernumModePublic#73]
I try to get into the ancient colosseum and the game gets stuck at "Saving world data"

**Comment by toasty599** [comment]
Read the template.

**Comment by RodrigoMz14** [comment]
https://github.com/DominicKarma/InfernumModePublic/assets/142472067/27ab3b8f-6ec8-489c-ad57-705cb342f673
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12435606/client.log)

Here are the logs and a video

**Comment by toasty599** [comment]
This does not seem to be an infernum issue.
