### ISSUE TITLE
Boss intro animation needs font customization

### ISSUE THREAD

**Issue by minejango2** [DominicKarma/InfernumModePublic#74]
Mostly because of localization, we need a function that applies a custom font to the boss intro animation. Since the font characters are limited, most non-English characters are not displayed.

(I used google translator. I'm really sorry if my words offended you.)

**Comment by toasty599** [comment]
This is very low priority, it may be done in future.

**Comment by minejango2** [comment]
Let me change the question. How do I submit the boss entrance animation font? Can I submit it in ttf/otf format?

[Font File (ttf)]
[neurimboGothicRegular.zip](https://github.com/InfernumTeam/InfernumModePublic/files/14085099/neurimboGothicRegular.zip)

(I need Unicode AC00 ~ D7A3 for Korean Localization)

I have very little knowledge about the font system used by Terraria, so I am asking a question here at the same time. Sorry for the inconvenience.
