### ISSUE TITLE
Calamitas supreme crash the game at the end of the combat

### ISSUE THREAD

**Issue by Galimauwu** [DominicKarma/InfernumModePublic#75]
Calamitas supreme at the very end of the combat,when she starts to do her monologue,the game freezes with an error,then if you accept the message,it took me out of the game with a bigger error log and closes the game

I tried to reinstall the mod and tmodloader and also verify the files,but nothing changes.
![ngkjj8mg72kb1](https://github.com/DominicKarma/InfernumModePublic/assets/143195334/808172a5-f8fa-4de5-b82b-917bd0830ff1)
![i
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12440338/client.log)
mage](https://github.com/DominicKarma/InfernumModePublic/assets/143195334/d11c69f6-a57e-4a8d-ba4c-34b9be66af12)

**Comment by Velvetttt** [comment]
I didn't get the bigger error log but I got the first error log about the contents/credits/textures/joy and it closes the game down and doesn't give me her loot bag too and doesn't count towards a kill...I've defeated her like 5 times now and I tried unsubscribing and subscribing the infernum mod in the workshop but still didn't work

**Comment by toasty599** [comment]
Should be fixed for next patch.
