### ISSUE TITLE
I can't attack The Devourer of Gods from the start of Phase 2 (only Multiplayer)

### ISSUE THREAD

**Issue by Eta7H** [DominicKarma/InfernumModePublic#76]
https://github.com/DominicKarma/InfernumModePublic/assets/128162836/579fe874-ccfe-4fbe-bc03-0d97ebb13286

When Phase 2 begins, the portal doesn't open, and it repeats the movements of Phase 1. After a while, it disappears, leaving only its head, which takes the first blow, but is then invulnerable, charging and disappearing and reappearing.

The bug does not occur in single player or death mode, so it seems to be an issue with Infernum mode.

Also, if an error occurs, other connected users will see an error message and crash.

**Comment by ZapGamer** [comment]
Hello, so i made the same post about a week ago and they fixed the problem in 2 days, all you need to do is wait for the next patch and It will be fixed.
