### ISSUE TITLE
Multiplayer completely broken post Lunar Pillars

### ISSUE THREAD

**Issue by Stachelbeere1248** [DominicKarma/InfernumModePublic#79]
All of Moonlord's eyes are invincible at low HP. (Health bar flickers between 0 and multiple tenthousands of HP)
Profaned Guardians cannot be spawned.
Providence throws error popups during the fight until eventually despawning at like 4/5 HP.
At that point we uninstalled Infernum Mode

**Comment by NeEba4** [comment]
100% Relatable. Praying for the next patch
