### ISSUE TITLE
Infernum / Fargo's Souls Eternity Compatibility Conflict w/Eater of Worlds (despawn on split)

### ISSUE THREAD

**Issue by PlayfulPiano** [DominicKarma/InfernumModePublic#8]
To my understanding, Infernum and Fargo's Souls is meant to be compatible in the sense that Infernum overwrites Souls' AI changes. With the Eater of Worlds fight, specifically, it seems that the act of a boss splitting into new "bosses" doesn't properly work, causing the boss to despawn / "die" without any dropped items nor continuation of the phases (in EoW's case, spltting to 2 then 4 of itself).

This is the only boss within Pre HM that I've dealt with issues so far when using both mods and both modes, as a reference. And if there are any other bosses with similar behavior in HM or later (haven't gotten to that yet), I would not be surprised if the same outcome occurs there, too.

https://github.com/DominicKarma/InfernumModePublic/assets/3158887/38460112-a2d2-4356-82eb-7b8b941b15ba

**Comment by toasty599** [comment]
Fargos is making a compatibility mod with Calamity. 'Til then, do not expect cross modding to work.

**Comment by PlayfulPiano** [comment]
Wait they are? This is the first time I've heard about this. I thought they were done with cross mod compatibility.
