### ISSUE TITLE
Fatal error during Providence fight and boss disappearing when "Lava is rising from below !"

### ISSUE THREAD

**Issue by Fatcowtntbandit2** [DominicKarma/InfernumModePublic#80]
When fighting providence for the first time after opening the game when you reach the moment where she does some kind of purple laser thingy (watch the video lol) an error occurs and something pops up. If you refight her after the error won't be there. It'll only appear the first time you reach that attack after opening the game.

Also, the boss disappears whenever you reach the "Lava is rising from below !" phase. Though I'm not sure this leaves behind any sort of logs, the boss just goes away.

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12448480/client.log)

**Error:**

https://github.com/DominicKarma/InfernumModePublic/assets/143346372/64325fdc-2734-429d-a365-f9efa962679b

**Boss disappearing:** 

https://github.com/DominicKarma/InfernumModePublic/assets/143346372/ca78e786-9862-4aa2-a328-8cf53a34bf88

_Calamity Mod Infernum Mode v1.9.28_

**Comment by toasty599** [comment]
You will need to do this fight on a new world on 1.9.29+.
