### ISSUE TITLE
No creative shock in profaned gardens and can't interact with altar or summon profaned guardians

### ISSUE THREAD

**Issue by Hyp3rSqu1d** [DominicKarma/InfernumModePublic#81]
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12449364/client.log)

![20230827191819_2](https://github.com/DominicKarma/InfernumModePublic/assets/71411657/755f4d38-2dc2-478c-8f72-7d4ffade76de)

As the title says the I can't summon the profaned guardians or read the altar in the profaned gardens at all. I also don't have creative shock. This was taken in a test world and not in the actual world I play on. but the results are still the same. I even tested it with different characters, different worlds, and reinstalling the mod and it got the same results every time.

**Comment by Yuurisuu** [comment]
This also happened to me. I tried to summon profaned  guardians and there is no interaction back after all.

**Comment by toasty599** [comment]
You will need to fight them in a new world created in version 1.9.29+ unfortunately.
