### ISSUE TITLE
King Slime Death Animation Soft Lock

### ISSUE THREAD

**Issue by TexasRazor** [DominicKarma/InfernumModePublic#84]
Upon killing King Slime, the game soft locks. You're unable to move and forced to watch king slime "die" in an endless loop.

https://github.com/DominicKarma/InfernumModePublic/assets/143393295/e85633bf-3ca3-4738-88b9-7fbb907eb056

[Natives.log](https://github.com/DominicKarma/InfernumModePublic/files/12452590/Natives.log)
[terrariasteamclient.log](https://github.com/DominicKarma/InfernumModePublic/files/12452591/terrariasteamclient.log)
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12452592/client.log)
[environment-client.log](https://github.com/DominicKarma/InfernumModePublic/files/12452593/environment-client.log)
[Launch.log](https://github.com/DominicKarma/InfernumModePublic/files/12452594/Launch.log)

**Comment by toasty599** [comment]
Mod conflict issue, disable mods til you find which is causing it, and don't use that mod with infernum.
