### ISSUE TITLE
Brimstone Elemental Causing Crash

### ISSUE THREAD

**Issue by PowerSurge05** [DominicKarma/InfernumModePublic#85]
Whenever I summon the Brimstone Elemental, either legitimately or with Cheat Sheet, the game crashes. I have narrowed Infernum down as the most likely culprit because the fight goes as normal without Infernum enabled. I have included my most recent client.log file from after I summon the Brimstone Elemental with Infernum enabled.

[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12459789/client.log)

**Comment by toasty599** [comment]
fixed in latest patch
