### ISSUE TITLE
Providence music wont stop if pause the game(with providence disappers and AEW error)

### ISSUE THREAD

**Issue by BookshelfScarlett** [DominicKarma/InfernumModePublic#86]
just like what title said, music wont stop if pause the game, causes music cannot sync to the whole fight

https://github.com/DominicKarma/InfernumModePublic/assets/143493496/83ee1465-2523-4f1c-97c0-67fdc2c87b77

btw providence disappers when entering the phase 2(Lava is rising from below!), in the world which created in 1.4.4 but **NOT** created in 1.4.3.

https://github.com/DominicKarma/InfernumModePublic/assets/143493496/2d8f2f1d-0ca0-47a4-bd9f-713f82bcb2ad

also when AEW(or Primordial Wyrm) dose a "cross" shape dashes would cause multiple errors, make the AEW "cross" shape attack invisibie.
![AEW bug](https://github.com/DominicKarma/InfernumModePublic/assets/143493496/f2c7f80c-3f5d-4257-909b-c2c99d8e65bf)

https://github.com/DominicKarma/InfernumModePublic/assets/143493496/f9758d1b-c76d-49a4-a783-6ef60e28f7f6

here's the log, though im not sure if the providence issues leaves something , but i would put it here.
[client.log](https://github.com/DominicKarma/InfernumModePublic/files/12462495/client.log)

**Comment by toasty599** [comment]
1) read the changelogs please, that was done for a reason.
2) make a new world
3) will fix
