### ISSUE TITLE
Profaned bosses/providence in a world created before .29

### ISSUE THREAD

**Issue by Geckoleon** [DominicKarma/InfernumModePublic#87]
The recent patch has made it so that the Profaned bosses will work in a newly created world, but still fail in a world created before .29. If this isn't fixable(and I'm guessing it has to do with world gen and won't be fixable), is there any chance there could be a debug item to set providence to having been defeated to allow for all the stuff providence opens up like the uelibloom ore and other? I don't want to give up my 200hr world that I've played in up till now

Edit: I realized right after posting this that I could simple go and beat providence in not-infernum mode to trigger the world state, but I'll leave this as a bug report that providence/profaned guardians don't work in a world generated before .29, at least for me

**Comment by ziolek23** [comment]
It happens to me too. It doesn't work in the new patch either.

**Comment by toasty599** [comment]
It is not a retroactive fix sadly. Like you mentioned, you can fight providence etc in death mode to mark her as dead, and use a new world to fight the Infernum fight.
