### ISSUE TITLE
Eidolists Spawning at the surface of the Sulphurous Seas

### ISSUE THREAD

**Issue by thefakeone27** [DominicKarma/InfernumModePublic#88]

**Comment by thefakeone27** [comment]
when i was making housing for sulfur pylon, tons of eidolists spawn and massacre me with their barrage of lasers which lags my pc aswell

**Comment by toasty599** [comment]
You will likely need a new world to properly fight them and the profaned bosses. However, I will prevent them spawning if their position data was lost, which seems to be the case here.
