### ISSUE TITLE
Bug with Sakura Bud not being able to transmute into Bloom

### ISSUE THREAD

**Issue by takeshipoggies** [DominicKarma/InfernumModePublic#89]
I believe there are no requirements for the Sakura Bud to transform into Bloom upon being dropped in the pond in the mini sakura biome, so I think it's a bug.
The item itself apparently doesn't recognize the place at all, it doesn't change its tooltip nor obviously becomes Sakura Bloom if I drop it in the water.

I'm sorry if it's been discussed already, didn't find it anywhere.

Here a screenshot to prove I'm in the biome but nothing changes.
![Screenshot 2023-08-31 121752](https://github.com/DominicKarma/InfernumModePublic/assets/62186122/ec436c25-a3bc-4aae-a0a7-dd18a4476eaf)

[here the client log](https://github.com/DominicKarma/InfernumModePublic/files/12485184/client.log) although I don't know how useful it could be.

**Comment by toasty599** [comment]
If this world was generated before 1.9.29 and after 1.9.27 or so, then you will need to generate a new world and use it there,
