### ISSUE TITLE
profaned guardians not spawning/profaned garden problem / unkillable moonlord in multiplayer / crash during Bereft Vassal

### ISSUE THREAD

**Issue by biallo1** [DominicKarma/InfernumModePublic#90]
1. profaned garden/guardians:

cant spawn profaned guadians in 1.9.28 world, can build/destroy block in profaned garden, cant spawn boss (i used proper item and location when trying). 
after update to .29 boss and location works fine but only in new generated worlds, is there a way to fix my world from 1.9.28?
copying things using cheatsheet didnt help. pls help :(

2. unkillable moonlord in multiplayer:

he doesnt drop eyes no matter damage/change phase , his hp bar gets stuck at some point, there are times his hp drops a little but then gets back to set amount - unkillable no matter how many tries/people on server (2 is enough), tried making standalone server, fixing few things in config but i think its mainly mod problem

3. when using infernum healthbars game crashes when Bereft Vassal has his "introduction", disabling infernum healthbars makes so game doesnt crash.

**Comment by toasty599** [comment]
Unfortunately any worlds generated in that version will not work with the profaned bosses, you have my apologies.
You can continue to use the world, and simply fight those bosses in a new one if you wish to keep playing on it.

**Comment by Xiarno** [comment]
@toasty599 What about unkillable Moon Lord in multiplayer?
This is still an issue.

**Comment by chaapz** [comment]
why is this post closed? it makes it difficult to find what issues have already been recorded.
