### ISSUE TITLE
Profaned Guardians don't spawn

### ISSUE THREAD

**Issue by PyreauGithub** [DominicKarma/InfernumModePublic#95]
I killed the moon lord and the dragonfolly, went to the profaned garden, step up on the cliff with the profaned shard but nothing happens, i precise that it was daytime when i tried to summon them. Also the panel on the center of the garden doesn't allow me to click on it : the message appear during 1 frame and instantly close.

**Comment by PyreauGithub** [comment]
I'm on 1.4.4 by the way, medium world, master mode (with Infernum Master and For the Worthy Patch mod)

**Comment by sasadness** [comment]
yeah im having the same issues

**Comment by PyreauGithub** [comment]
we can't beat the boss on this world, so i created a new one just to beat
it with the new version of the mod, also providence will not work i
recommend you to do providence and the guardians on the new world you
created
