### ISSUE TITLE
Potential softlock with teleportation potion and the providence arena(?)

### ISSUE THREAD

**Issue by DogsTongue** [DominicKarma/InfernumModePublic#96]
Using a teleportation potion can cause the player to be teleported into what I assume to be the arena for Providence(Unrelated to the bug report but it looks really good). Sleeping on one of the beds here before getting kicked out can cause the players spawn to be set inside the area. When the player is kicked out and dies they will then respawn back at the area they were kicked out to, which can be deep in lava and result in unavoidable death depending on position and equipment.

As a result, it is possible for a player to unintentionally end up in a death loop, soft locking the game. The only theoretical part is being unable to escape with the players current items, as I luckily had a grappling hook, 400 health and mobility accessories. Images attached:

Standing outside the area, there is a crystal blocking the path:
![InfernumReport1](https://github.com/DominicKarma/InfernumModePublic/assets/77945527/ad5c3fda-40eb-4105-8c76-a2993662ac84)

Respawning submerged in lava:
![InfernumReport2](https://github.com/DominicKarma/InfernumModePublic/assets/77945527/afade816-7364-4eb0-8f38-b2064150832a)

Map showing respawn point inside the structure:
![InfernumReport3](https://github.com/DominicKarma/InfernumModePublic/assets/77945527/add226cf-bc23-4dfd-b7af-ba327acd84f2)

**Comment by toasty599** [comment]
While very funny, you would have to deliberately cause this, and you can easily solve it by using a different world to get lava proof gear.

**Comment by DogsTongue** [comment]
I would like to note that I in fact did not do this deliberately, I'm just stupid
