### ISSUE TITLE
profaned guardians won't spawn

### ISSUE THREAD

**Issue by a-dud** [DominicKarma/InfernumModePublic#97]
whenever i try to spawn the profaned guardians it does not work. I killed ML multiple times, i tried at night, at day, in the hallow, in the underworld, at the cliff in the palace, tried reading the scripture, it didn't work. Even using cheat sheat and HERO's mod to spawn them in didn't work. Can you please fix this bug.

**Comment by sasadness** [comment]
im having the same problem

**Comment by toasty599** [comment]
#90
