### ISSUE TITLE
Underworld Bio-Center Lab spawning in the biome on the right side of the underworld

### ISSUE THREAD

**Issue by Fatcowtntbandit2** [DominicKarma/InfernumModePublic#98]
The Underworld Bio-Center Lab can spawn in the biome on the right side of the underworld. It is then impossible to enter or remove it since I have the Creative Shock debuff. The structure is kind of the in the way for the profaned guardians fight as well (it doesnt help at the very least).

![image](https://github.com/DominicKarma/InfernumModePublic/assets/143346372/6e373ca6-2426-4633-8892-717c4cdd4336)

_Calamity Mod Infernum Mode v1.9.30_

**Comment by toasty599** [comment]
Use a large world.
