### ISSUE TITLE
Infernum refuses to load during game startup

### ISSUE THREAD

**Issue by ProfLeafeon** [DominicKarma/InfernumModePublic#99]
![image](https://github.com/DominicKarma/InfernumModePublic/assets/143915558/8c273d67-82b7-4d06-95ce-6248c1b89755)

tModloader claims that the mod is on the wrong version when it was working fine a the day before. I thought it might be useful to report it, since one of my friends had the same problem. Cheers!

**Comment by Flairey** [comment]
Seems like the new version of calamity broke it ¯\_(ツ)_/¯.
You can follow these steps [here](https://discord.com/channels/225030931008847874/1147285136539385866/1147285136539385866) if you're in the [official calamity discord](https://discord.gg/Calamity) to downgrade one version of calamity manually.

**Comment by toasty599** [comment]
update your mod.
